name: examples
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  bun-postgresql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: "examples/bun-postgres"
            qs: "postgresql"
    steps:
    - uses: actions/checkout@v4
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.24.0'
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - uses: sqlc-dev/action-setup-postgres@master
      with:
        postgres-version: "16"
      id: postgres
    - run: bun install
      working-directory: ${{ matrix.dir }}
    - run: psql -f schema.sql "$DATABASE_URL"
      working-directory: examples/authors/postgresql
      env:
        DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}?sslmode=disable
    - run: bun run src/main.ts
      working-directory: ${{ matrix.dir }}
      env:
        DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}?sslmode=disable

  node-postgresql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: "examples/node-postgres"
            qs: "postgresql"
    steps:
    - uses: actions/checkout@v4
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.24.0'
    - uses: actions/setup-node@v4
    - uses: sqlc-dev/action-setup-postgres@master
      with:
        postgres-version: "16"
      id: postgres
    - run: npm install
      working-directory: ${{ matrix.dir }}
    - run: npx tsc
      working-directory: ${{ matrix.dir }}
    - run: psql -f schema.sql "$DATABASE_URL"
      working-directory: examples/authors/postgresql
      env:
        DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}?sslmode=disable
    - run: node ./src/main.js
      working-directory: ${{ matrix.dir }}
      env:
        DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}?sslmode=disable
