name: Rebase Upstream
on:
  schedule:
  - cron: "0 11 * * 1"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 100 
    - uses: imba-tjd/rebase-upstream-action@master
      with: 
        branch: main

