name: tests
on:
  workflow_run:
    workflows: [ ci ]
    types: [ completed ]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: [ ci ]
    steps:
      - uses: actions/checkout@v4
      - uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: '1.27.0'
      - name: Download WASM artifact
        uses: actions/download-artifact@v3
        with:
          name: plugin-wasm
      - name: Run tests
        run: cd test && bun run test
